DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_ID_SQ;
CREATE TABLE FRIEND(
    ID NUMBER(10),
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(30) UNIQUE,
    PRIMARY KEY(ID)
);
CREATE SEQUENCE FRIEND_ID_SQ MAXVALUE 9999999999 NOCACHE NOCYCLE;
-- MAPPER에 (REPSITORY)에 들어갈 SQL문
-- ID=save
INSERT INTO FRIEND VALUES (FRIEND_ID_SQ.NEXTVAL, '홍길동', '010-9999-9999');
-- ID=findByTel
SELECT * FROM FRIEND WHERE TEL='010-9999-9999';
-- ID=findAll
SELECT * FROM FRIEND;
-- ID=findByID
SELECT * FROM FRIEND WHERE ID=1;
--ID=deleteAll
COMMIT;
DELETE FROM FRIEND;
ROLLBACK;
-- ID=deleteOne
DELETE FROM FRIEND WHERE ID=3;
ROLLBACK;