-- table및 시퀀스 제거
DROP TABLE MVCBOARD;
DROP SEQUENCE MVCBOARD_SEQ;
-- table및 시퀀스 생성
CREATE TABLE MVCBOARD (
    BID NUMBER(6) PRIMARY KEY, --글번호
    BNAME VARCHAR2(50) NOT NULL, --이름
    BTITLE VARCHAR2(100) NOT NULL, --글제목
    BCONTENT VARCHAR2(1000), --글본문
    BDATE DATE DEFAULT SYSDATE NOT NULL, --작성시점
    BHIT NUMBER(6) DEFAULT 0 NOT NULL, --조회수
    BGROUP NUMBER(6) NOT NULL, --글그룹
    BSTEP NUMBER(3) NOT NULL, --그룹내 출력순서
    BINDENT NUMBER(3) NOT NULL, --들여쓰기
    BIP VARCHAR2(20) NOT NULL --글쓰기 요청한IP
    );
CREATE SEQUENCE MVCBOARD_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;
-- 검색
SELECT * FROM MVCBOARD;
-- dummy data (3개 이상 - 2개원글 +1개 답변글)
INSERT INTO MVCBOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVCBOARD_SEQ.NEXTVAL, '김', '제목1', '내용', MVCBOARD_SEQ.CURRVAL, 0, 0, '192.168.0.1');
INSERT INTO MVCBOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVCBOARD_SEQ.NEXTVAL, '이', '제목2', '내용2', MVCBOARD_SEQ.CURRVAL, 0, 0, '192.168.0.1');
INSERT INTO MVCBOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVCBOARD_SEQ.NEXTVAL, '박', '제목3', '내용3', MVCBOARD_SEQ.CURRVAL, 0, 0, '192.168.0.1');
INSERT INTO MVCBOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVCBOARD_SEQ.NEXTVAL, '홍', '제목2-1', '내용4', 2, 1, 1, '192.168.0.1');

-- dao에 들어갈 query
-- 1. 글목록(startRow부터endRow)
SELECT * FROM MVCBOARD ORDER BY BGROUP DESC, BSTEP;
SELECT ROWNUM RN, A.*
    FROM(SELECT * FROM MVCBOARD ORDER BY BGROUP DESC, BSTEP) A;
SELECT * 
    FROM (SELECT ROWNUM RN, A.*
    FROM(SELECT * FROM MVCBOARD ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 1 AND 4;
-- 2. 글갯수
SELECT COUNT(*) CNT FROM MVCBOARD;
-- 3. 원글쓰기 (bname, btitle, bcontent, bip, bgroup은 글번호, bstep과bindent는0)
INSERT INTO MVCBOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVCBOARD_SEQ.NEXTVAL, '라', '제목4', '내용5', MVCBOARD_SEQ.CURRVAL, 0, 0, '192.168.0.1');
-- 4. bid로 조회수 1올리기
UPDATE MVCBOARD SET BHIT = BHIT+1 WHERE BID=1;
-- 5. bid로 dto가져오기
SELECT * FROM MVCBOARD WHERE BID=1;
-- 6. 글수정 (특정bid의 bname, btitle, bcontent, bip 수정)
UPDATE MVCBOARD
    SET BNAME = '김',
        BTITLE = '제목1',
        BCONTENT = '내용1',
        BIP = '111.11.11'
    WHERE BID=1;
-- 7. 글삭제 (특정 bid 삭제)
COMMIT;
DELETE FROM MVCBOARD WHERE BID=1;
ROLLBACK;
-- 8. 답변글 저장 전단계(엑셀 a단계)
UPDATE MVCBOARD SET BSTEP = BSTEP+1
    WHERE BGROUP=1 AND BSTEP>0;
-- 9. 답변글 저장
INSERT INTO MVCBOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (MVCBOARD_SEQ.NEXTVAL, '롱', '글1-1', '내용6', 1, 1, 1, '192.168.0.1');
COMMIT;