-- DROP & CREATE SEQUENCE, TABLE
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
CREATE TABLE CUSTOMER(
    CID VARCHAR2(50) PRIMARY KEY,
    CPW VARCHAR2(50) NOT NULL,
    CNAME VARCHAR2(50) NOT NULL,
    CTEL VARCHAR2(50),
    CEMAIL VARCHAR2(50),
    CADDRESS VARCHAR2(50),
    CBIRTH DATE,
    CGENDER VARCHAR2(1),
    CRDATE DATE DEFAULT SYSDATE);