-- drop & create테이블(freind-no, name, tel)과 시퀀스(friend_no_seq)
DROP SEQUENCE SEQ;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;
CREATE TABLE FRIENDS(
    FNUM NUMBER(10) PRIMARY KEY,
    FNAME VARCHAR2(50) NOT NULL,
    FTEL VARCHAR2(50) );
-- dao에 들어갈query
INSERT INTO FRIENDS(FNUM, FNAME, FTEL)
    VALUES(SEQ.NEXTVAL, '홍길동', '010-9999-9999');

INSERT INTO FRIENDS(FNUM, FNAME, FTEL)
    VALUES(SEQ.NEXTVAL, '신길동', '010-8999-9999');
--친구추가
--친구들 출력
SELECT * FROM FRIENDS;
select * from friends order by FNUM;