--[VIII] Sequence : 순차번호 생성기. 대부분인위적인 PK사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 --1부터시작(기본값)
    INCREMENT BY 1-- 1씩 증가(기본값)
    MAXVALUE 9999 --최대값
    MINVALUE 1 -- 최소값(기본값)
    NOCACHE
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; --다음 순차번호 생성
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; --시퀀스의 현재값
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY, --시퀀스를 사용해서 값이 들어갈 필드
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE, -- NULL허용, NULL이 아니면 유일한값
    ADDRESS VARCHAR2(300),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울 서대문'); -- 몇번실행가능
SELECT * FROM FRIEND;
--INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    --VALUES (FRIEND_SEQ.NEXTVAL, NULL, '010-9999-9999', '서울마포'); --에러
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-9999-9999', '서울마포'); -- 에러(UNIQUE) 전화번호중복
-- EX. 초기값 101부터 최대값 999,999까지 1씩 증가하는 TEST_SEQ 시퀀스를 생성하고 시퀀스를 사용하시오
CREATE SEQUENCE TEST_SEQ
    START WITH 101
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL; --시퀀스 사용전에는 현재값을 조회할 수 없음
SELECT TEST_SEQ.NEXTVAL FROM DUAL;-- 시퀀시 사용
-- EX. 시퀀스 NO_SEQ 초기값 1부터 999까지 1씩 증가하는 사용:
    -- SYSDATE 'RRMMDD'추출 => ' 230728'|| 시퀀스 생성수(1) ->001
DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ MAXVALUE 999 NOCACHE NOCYCLE;
SELECT TO_CHAR(SYSDATE, 'RRMMDD') FROM DUAL;--230728
SELECT TO_CHAR(NO_SEQ.NEXTVAL, '000') FROM DUAL;--001
SELECT TO_CHAR(SYSDATE, 'RRMMDD') || TRIM(TO_CHAR(NO_SEQ.NEXTVAL, '000')) NO FROM DUAL;--'230728005'


--시험
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(2) PRIMARY KEY,
    LEVELNAME VARCHAR2(8) NOT NULL
);
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
    START WITH 1 --1부터시작(기본값)
    INCREMENT BY 1-- 1씩 증가(기본값)
    MINVALUE 1 -- 최소값(기본값)
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE MEMBER(
    MNO NUMBER(5) PRIMARY KEY,
    MNAME VARCHAR2(50) NOT NULL,
    MPW VARCHAR2(8),
    MMAIL VARCHAR2(50) UNIQUE,
    MPOINT NUMBER(5) CHECK(MPOINT>=0),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(2)
);
SELECT * FROM MEMBER;
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER_LEVEL VALUES(-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES(0, '일반');
INSERT INTO MEMBER_LEVEL VALUES(1, '실버');
INSERT INTO MEMBER_LEVEL VALUES(2, '골드');
INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa' ,'hong@hong.com', 0, '22/03/10', 0 );
INSERT INTO MEMBER VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb' ,'shin@shin.com', 1000, '22/04/01', 1 );

SELECT MNO mNO, MNAME mNAME, TO_CHAR(MRDATE, 'YYYY-MM-DD')mRDATE, MMAIL mMAIL, MPOINT mPOINT, LEVELNAME||'고객' levelname
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO=L.LEVELNO;
    
DROP TABLE ORDERDETAIL;
DROP TABLE ODER;
DROP TABLE CART;
DROP TABLE PRODUCT;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    MID VARCHAR2(10) PRIMARY KEY,
    MNAME VARCHAR2(50) NOT NULL,
    MTEL VARCHAR2(10) NOT NULL,
    MADDRESS VARCHAR2(50) NOT NULL,
    MEMAIL VARCHAR2(50) NOT NULL
);

CREATE TABLE PRODUCT(
    PCODE VARCHAR2(10) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    PPRICE VARCHAR2(20) NOT NULL, 
    PINVEN NUMBER(10) NOT NULL
);
DROP SEQUENCE CNO;
CREATE SEQUENCE CNO
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
CREATE TABLE CART(
    CNO NUMBER(5) PRIMARY KEY,
    MID VARCHAR2(10) REFERENCES MEMBER(MID) NOT NULL,
    SUM NUMBER(30) NOT NULL,
    PCODE VARCHAR2(10) REFERENCES PRODUCT(PCODE) NOT NULL,
    PNAME VARCHAR2(50) NOT NULL,
    CPRODUCTNUM VARCHAR2(50) NOT NULL
);
DROP SEQUENCE ONO;
CREATE SEQUENCE ONO
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
CREATE TABLE ORDERS(
    ONO NUMBER(5) PRIMARY KEY,
    MID VARCHAR2(10) REFERENCES MEMBER(MID) NOT NULL,
    ONAME VARCHAR2(50) NOT NULL,
    OADDRESS VARCHAR2(50) NOT NULL,
    OTEL VARCHAR2(10) NOT NULL,
    ODATE DATE DEFAULT SYSDATE
);
CREATE TABLE ORDERDETAIL(
    ONO NUMBER(5) PRIMARY KEY,
    PCODE VARCHAR2(10) REFERENCES PRODUCT(PCODE) NOT NULL,
    PRICE NUMBER(20) NOT NULL,
    SUM NUMBER(30) NOT NULL
);



INSERT INTO MEMBER VALUES ('ABC', '홍길동', '010-9999-9999', '서울시 서대문구 대현동', 'ABC@ABC.COM');
INSERT INTO MEMBER VALUES ('DEF', '김길동', '010-8888-8888', '경기도 수원시', 'DEF@DEF.COM');
INSERT INTO PRODUCTS VALUES ('A1', '맥주', '3000', 100);
INSERT INTO PRODUCTS VALUES ('A2', '마스크', '200', 100);
INSERT INTO PRODUCTS VALUES ('B1', '땅콩', '3000', 100);
INSERT INTO PRODUCTS VALUES ('B2', '오징어', '5000', 100);
INSERT INTO PRODUCTS VALUES ('C1', '소독약', '7000', 100);
 
INSERT INTO CART VALUES (CNO.NEXVAL, "ABC"