-- Emp.xml id=empList
SELECT * FROM EMP ORDER BY EMPNO; --출력시준
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM EMP ORDER BY EMPNO) A)
    WHERE RN BETWEEN 6 AND 10;
-- EMP.XML의 id=empDeptList
SELECT E.*, DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO ORDER BY EMPNO; --출력기준
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT E.*, DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO ORDER BY EMPNO) A)
    WHERE RN BETWEEN 6 AND 10;

-- Dept.xml의 id=TOTCNT
SELECT COUNT(*) FROM EMP;
-- Emp.xml의 id=detail
SELECT * FROM EMP WHERE EMPNO=7369;
-- Emp.xml의 id=managerList
SELECT * FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP);
-- Emp.xml의 id=insert
INSERT INTO EMP VALUES (9000, '홍길동', 'MANAGER', 7902, '23/11/10', 9000, 100, 40);
-- Emp.xml의 id=update
UPDATE EMP SET
    ENAME= '신길동',
    JOB = 'SALESMAN',
    MGR = 7902,
    HIREDATE = '23/11/01',
    SAL = 8000,
    COMM = 900,
    DEPTNO = 40
    WHERE EMPNO = 9000;
    
-- Emp.xml의 id=delete
DELETE FROM EMP WHERE EMPNO=9000;
COMMIT;


-- DEPT.xml의 id=deptList
SELECT * FROM DEPT;










