DROP TABLE FILEBOARD;
DROP SEQUENCE FILEBOARD_SEQ;
DROP TABLE MVC_MEMBER;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
CREATE SEQUENCE FILEBOARD_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
--테이블 생성
CREATE TABLE FILEBOARD(
    FID NUMBER(6) PRIMARY KEY,
    FTITLE VARCHAR2(100) NOT NULL,
    FCONTENT VARCHAR2(4000),
    FFILENAME VARCHAR2(100),
    FRDATE DATE DEFAULT SYSDATE NOT NULL,
    FHIT NUMBER(6) NOT NULL,
    FGROUP NUMBER(6) NOT NULL,
    FSTEP NUMBER(6) NOT NULL,
    FINDENT NUMBER(6) NOT NULL,
    FIP VARCHAR2(30) NOT NULL);
SELECT * FROM FILEBOARD;