-- source/06_jsp/model2ex 프로젝트는 글삭제시 해당글만 삭제
-- source/07_jQuery/model2ex 프로젝트는 글삭제시 답변글들까지 삭제

-- 글삭제시 답변들까지 함께 삭제한 후 step 재조정 (step 재조정은 생략 가능)

DROP TABLE MEMO;
CREATE TABLE MEMO (
  ID NUMBER(4) PRIMARY KEY,
  TITLE VARCHAR2(100) NOT NULL,
  MGROUP NUMBER(4) NOT NULL,
  MSTEP  NUMBER(2) NOT NULL,
  MINDENT NUMBER(2) NOT NULL
);
DROP SEQUENCE MEMO_SEQ;
CREATE SEQUENCE MEMO_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;

-- 더미 데이터 
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글1', MEMO_SEQ.CURRVAL, 0, 0);
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2', MEMO_SEQ.CURRVAL, 0, 0);
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글3', MEMO_SEQ.CURRVAL, 0, 0);
SELECT * FROM MEMO ORDER BY MGROUP DESC, MSTEP;
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글1-1', 1, 1, 1);-- 글1의 첫 답변
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-1', 2, 1, 1); -- 글2의 첫 답변
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글3-1', 3, 1, 1); -- 글3의 첫 답변
SELECT * FROM MEMO ORDER BY MGROUP DESC, MSTEP;
UPDATE MEMO SET MSTEP = MSTEP+1 WHERE MGROUP=2 AND MSTEP>0; ---┐글2의 두번째 답변
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-2', 2, 1, 1);--┘
UPDATE MEMO SET MSTEP = MSTEP + 1 WHERE MGROUP=2 AND MSTEP>0;---┐글2의 세번째 답변
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-3', 2, 1, 1); --┘
SELECT * FROM MEMO ORDER BY MGROUP DESC, MSTEP;
UPDATE MEMO SET MSTEP = MSTEP + 1 WHERE MGROUP=2 AND MSTEP>1;  ---┐글2-3의 첫번째 답변
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글2-3-1', 2, 2, 2); --┘
UPDATE MEMO SET MSTEP = MSTEP + 1 WHERE MGROUP=3 AND MSTEP>0;  ---┐글3의 두번째 답변
INSERT INTO MEMO VALUES (MEMO_SEQ.NEXTVAL, '글3-2',3, 1, 1);--┘
SELECT * FROM MEMO ORDER BY MGROUP DESC, MSTEP;
SELECT LPAD(SUBSTR(ENAME, 1,2), LENGTH(ENAME), '*') FROM EMP;
SELECT LPAD('└', 4, ' ') FROM DUAL;
SELECT ID, 
    LPAD('└', (MINDENT*2), ' ')||TITLE title, MGROUP, MSTEP, MINDENT 
    FROM MEMO ORDER BY MGROUP DESC, MSTEP;
-- 글 2-3(8번글)을 지울 경우, 글 2-3-1도 삭제 (DTO : ID(8) 글2-3/2(BGROUP)/ 1(BSTEP) / 1(BINDENT)
SELECT MIN(MSTEP) FROM MEMO WHERE MGROUP=2 AND MSTEP>1 AND MINDENT<=1; -- 서브쿼리(mstep이 3이전까지 지우려함)
DELETE FROM MEMO WHERE MGROUP=2 AND (MSTEP>=1 AND 
  MSTEP<(SELECT MIN(MSTEP) FROM MEMO WHERE MGROUP=2 AND MSTEP>1 AND MINDENT<=1));
UPDATE MEMO SET MSTEP = MSTEP-2 WHERE MGROUP=2 AND MSTEP>1; -- 생략 가능(2은 위의 DELETE문 수행결과)

-- 글1-1을 지울 경우 (DTO : ID(4), 글1-1, 1(BGROUP) / 1(BSTEP)  / 1(BINDENT)
SELECT MIN(MSTEP) FROM MEMO WHERE MGROUP=1 AND MSTEP>1 AND MINDENT<=1; -- 서브쿼리결과가 NULL
SELECT NVL(MIN(MSTEP),99) FROM MEMO WHERE MGROUP=1 AND MSTEP>1 AND MINDENT<=1; -- 서브쿼리
DELETE FROM MEMO WHERE MGROUP=1 AND (MSTEP>=1 AND 
  MSTEP<(SELECT NVL(MIN(MSTEP),99) FROM MEMO WHERE MGROUP=1 AND MSTEP>1 AND MINDENT<=1));
UPDATE MEMO SET MSTEP = MSTEP-1 WHERE MGROUP=1 AND MSTEP>1; -- 생략가능(1은 위의 DELETE문 수행결과)
--확인용
SELECT * FROM MEMO ORDER BY MGROUP DESC, MSTEP;
SELECT ID, 
    LPAD('└', (MINDENT*2), ' ')||TITLE, MGROUP, MSTEP, MINDENT 
    FROM MEMO ORDER BY MGROUP DESC, MSTEP;

-- 글 2번 글 경우 (DTO : ID(2), 글2, 2(BGROUP) / 0(BSTEP) / 0(BINDENT)
DELETE FROM MEMO WHERE MGROUP=2 AND (MSTEP>=0 AND 
  MSTEP<(SELECT NVL(MIN(MSTEP),99) FROM MEMO WHERE MGROUP=0 AND MSTEP>0 AND MINDENT<=0));
UPDATE MEMO SET MSTEP = MSTEP-3 WHERE MGROUP=2 AND MSTEP>0; -- 생략가능 (3은 위의 DELETE문 수행결과)
--확인용
SELECT * FROM MEMO ORDER BY MGROUP DESC, MSTEP;
SELECT ID, 
    LPAD('└', (MINDENT*2), ' ')||TITLE, MGROUP, MSTEP, MINDENT 
    FROM MEMO ORDER BY MGROUP DESC, MSTEP;