-- DDL & dummy data

-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_PNO_SQ;

-- 테이블 및 시퀀스 생성
CREATE TABLE JOB (
    JNO NUMBER(2,0) PRIMARY KEY,
    JNAME VARCHAR2(10) UNIQUE
);
CREATE SEQUENCE PERSON_PNO_SQ MAXVALUE 99999 NOCACHE NOCYCLE;
CREATE TABLE PERSON(
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    JNO NUMBER(2,0) REFERENCES JOB(JNO) NOT NULL,
    KOR NUMBER(3) CHECK(KOR BETWEEN 0 AND 100),
    ENG NUMBER(3) CHECK(ENG BETWEEN 0 AND 100),
    MAT NUMBER(3) CHECK(MAT>=0 AND MAT<=100)
);

-- 더미데이터 INSERT
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '개그맨');
SELECT * FROM JOB;
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '정우성',10, 90,80,81);
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '박세영',10, 80,90,80);
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '배수지',20, 20,90,90);
SELECT * FROM PERSON;
COMMIT;