-- insert
--EX1.

--EX2. 부서번호 중복체크 후 INSERT
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=60; -- 중복체크하기 위한SELECT
INSERT INTO DEPT VALUES (50, 'IT', 'SEOUL');
SELECT * FROM DEPT;
COMMIT;

-- UPDATE
--ex1.
UPDATE DEPT SET DNAME='CS', LOC='INCHON' WHERE DEPTNO=70;
SELECT * FROM DEPT;
--ex2. 부서번호 유무 확인후 update;
SELECT * FROM DEPT WHERE DEPTNO=60;
UPDATE DEPT SET DNAME='CS', LOC='INCHON' WHERE DEPTNO=60;
COMMIT;
-- delete
DELETE FROM DEPT WHERE DEPTNO=70;
SELECT * FROM DEPT;