-- DROP & CREATE SEQUENCE, TABLE 
CREATE TABLE BOOK(
  bID    NUMBER(7) PRIMARY KEY,
  bTITLE VARCHAR2(100) NOT NULL, -- 책이름
  bPRICE NUMBER(6)     NOT NULL, -- 책가격
  bIMAGE1 VARCHAR2(100) NOT NULL, -- 책 대표 이미지
  bIMAGE2 VARCHAR2(100) NOT NULL, -- 책 부가 이미지
  bCONTENT VARCHAR2(4000), -- 책설명(4000초과시 CLOB)
  bDISCOUNT NUMBER(3) NOT NULL,   -- 할인율
  bRDATE    DATE DEFAULT SYSDATE NOT NULL
);
CREATE SEQUENCE BOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
-- 고객 테이블
DROP TABLE FILEBOARD;
DROP TABLE CUSTOMER;
DROP TABLE BOOK;
DROP SEQUENCE FILEBOARD_SEQ;
DROP SEQUENCE BOOK_SEQ;
CREATE TABLE CUSTOMER (
  cID      VARCHAR2(50) PRIMARY KEY,
  cPW      VARCHAR2(50) NOT NULL,
  cNAME    VARCHAR2(50) NOT NULL,
  cTEL     VARCHAR2(50),
  cEMAIL   VARCHAR2(50),
  cADDRESS VARCHAR2(50),
  cBIRTH   DATE,
  cGENDER  VARCHAR2(1)  CHECK(cGENDER='m' OR cGENDER='f'),
  cRDATE   DATE DEFAULT SYSDATE NOT NULL
);
-- 파일첨부답변글게시판
CREATE TABLE FILEBOARD(
    fID     NUMBER(6) PRIMARY KEY,    -- 글번호
    cID      VARCHAR2(50) REFERENCES CUSTOMER(cID),
    fTITLE   VARCHAR2(100) NOT NULL, -- 글제목
    fCONTENT VARCHAR2(1000), -- 글본문
    FILENAME VARCHAR2(100), -- 첨부파일
    fHIT    NUMBER(6) DEFAULT 0,     -- 글 조회수
    fPW     VARCHAR2(50) NOT NULL,-- 글 삭제시 쓸 비번
    fGROUP  NUMBER(6) NOT NULL,  -- 글그룹(원글의 경우 글번호로/답변글일경우 원글의 BGROUP로)
    fSTEP   NUMBER(2) NOT NULL, -- 글그룹내 출력 순서(원글 0)
    fINDENT NUMBER(2) NOT NULL,  -- 글 LIST 출력시 글 제목 들여쓰기 정도(원글0)
    fIP     VARCHAR2(50) NOT NULL, -- 글 쓴 컴퓨터의 IP
    fRDATE   DATE DEFAULT SYSDATE NOT NULL -- 글 작성시점
);
CREATE SEQUENCE FILEBOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
